import { Component } from '@angular/core';
import { ProductCardComponent } from '../product-card/product-card.component';

@Component({
  selector: 'app-products-gallery',
  imports: [ProductCardComponent],
  templateUrl: './products-gallery.component.html',
  styleUrl: './products-gallery.component.scss',
})
export class ProductsGalleryComponent {
  products = [
    {
      link: '#',
      imageFront: 'carte-cadeau-visionnaire.webp',
      imageBack: 'carte-cadeau-visionnaire.webp',
      altText: 'Gift card',
      title: 'CARTE CADEAU VISIONNAIRE',
      sizes: ['40,0€', '70,0€', '100,0€'],
      price: '199,99',
      onSale: false,
    },
    {
      link: '#',
      imageFront: 'hoodie.webp',
      imageBack: 'hoodie_back.webp',
      altText: 'blue puffer hoodie',
      title: 'PUFFER MOUVEMENT BLUE',
      sizes: ['XXS', 'XS', 'S', 'M', 'L', 'XL', 'XXL'],
      price: '199,99',
      onSale: false,
    },
    {
      link: '#',
      imageFront: 'puffer_green.webp',
      imageBack: 'puffer_green_back.webp',
      altText: 'green puffer hoodie',
      title: 'PUFFER MOUVEMENT GREEN',
      sizes: ['XXS', 'XS', 'S', 'M', 'L', 'XL', 'XXL'],
      price: '199,99',
      onSale: false,
    },
    {
      link: '#',
      imageFront: 'puffer_vissionaire_creme.webp',
      imageBack: 'puffer_vissionaire_creme_back.webp',
      altText: 'VISSIONAIRE creme hoodie',
      title: 'PUFFER visionnaire creme',
      sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
      price: '126,00',
      onSale: true,
      previousPrice: '180,00',
    },
    {
      link: '#',
      imageFront: 'puffer_vissionaire_noir_back.webp',
      imageBack: 'puffer_vissionaire_noir.webp',
      altText: 'VISSIONAIRE black hoodie',
      title: 'PUFFER visionnaire noir',
      sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
      price: '126,00',
      onSale: true,
      previousPrice: '180,00',
    },

    {
      link: '#',
      imageFront: 'leviosaa.webp',
      imageBack: 'leviosaa_back.webp',
      altText: 'VISSIONAIRE and harry potter collab t-shirt',
      title: 'T-shirt vintage',
      sizes: ['xxs', 'XS', 'S', 'M', 'L', 'XL', 'XXL'],
      price: '27,00',
      onSale: true,
      previousPrice: '45,00',
    },
    {
      link: '#',
      imageFront: 'dobby_marron.webp',
      imageBack: 'dobby_marron_back.webp',
      altText: 'brown dobby from harry potter coat',
      title: 'Pull dobby marron',
      sizes: ['XXS', 'XS', 'S', 'M', 'L', 'XL', 'XXL'],
      price: '85,00',
      onSale: false,
    },
    {
      link: '#',
      imageFront: 'dobby_rose.webp',
      imageBack: 'dobby_rose_back.webp',
      altText: 'rose dobby from harry potter coat',
      title: 'Pull dobby rose',
      sizes: ['XXS', 'XS', 'S', 'M', 'L', 'XL', 'XXL'],
      price: '85,00',
      onSale: false,
    },
    {
      link: '#',
      imageFront: 'dobby_skyblue.jpg',
      imageBack: 'dobby_skyblue_back.jpg',
      altText: 'sky blue dobby from harry potter coat',
      title: 'Pull dobby bleu',
      sizes: ['XXS', 'XS', 'S', 'M', 'L', 'XL', 'XXL'],
      price: '85,00',
      onSale: false,
    },
    {
      link: '#',
      imageFront: 'dobby_socks_brown.webp',
      imageBack: 'dobby_socks_brown_back.webp',
      altText: 'Brown free dobby from harry potter socks',
      title: 'CHAUSSETTE DOBBY MARRON',
      sizes: ['36-41', '42-46'],
      price: '14,00',
      onSale: false,
    },
    {
      link: '#',
      imageFront: 'dobby_socks_noir.webp',
      imageBack: 'dobby_socks_noir_back.webp',
      altText: 'Black free dobby from harry potter socks',
      title: 'CHAUSSETTE DOBBY noir',
      sizes: ['36-41', '42-46'],
      price: '14,00',
      onSale: false,
    },
    {
      link: '#',
      imageFront: 'haggrid_hoodie_noir.webp',
      imageBack: 'haggrid_hoodie_noir_back.webp',
      altText: 'Black hagrid hoddie from harry potter',
      title: 'hoodie hagrid noir',
      sizes: ['XXS', 'XS', 'S', 'M', 'L', 'XL', 'XXL'],
      price: '75,00',
      onSale: false,
    },
  ];
}
